# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14d68fe7abb98a0cbddf54430ed3ca92361c31dcad222789d230eee5b2326f764668cdb79bda6fb976ed171b78cc855ae72d9514c6d05555c931e7a303a76b42

test:
  secret_key_base: 4e78dccab9baf6483e742e5e173c8d14b1a055b6e39e0ce7b5b653ac6e7f93eeeec3834e391c1faa296617d525d7e5806f03ae8ab5f0fbea9fe1d82f88d08f3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
